version: '3.8'

services:
  # 1. La Base de Données Centrale (Le centre de mémoire de la Tour de Contrôle)
  db:
    # On passe sur PostgreSQL, le moteur le plus robuste et recommandé pour Python/FastAPI
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: fleetguard_admin
      POSTGRES_PASSWORD: super_secret_password
      POSTGRES_DB: fleetguard_db
    ports:
      - "5432:5432"
    volumes:
      - central_data:/var/lib/postgresql/data

  # 2. L'API Backend (Le moteur de surveillance en Python)
  api:
    image: python:3.11-slim
    restart: always
    working_dir: /app
    env_file:
      - .env
    volumes:
      # Synchronise en temps réel ton dossier local "./backend" avec le conteneur
      - ./backend:/app
    ports:
      - "8000:8000" # Ton API sera accessible sur http://localhost:8000
    depends_on:
      - db
    # Installe les bibliothèques requises et lance le serveur avec rechargement automatique
    command: sh -c "pip install fastapi uvicorn sqlalchemy psycopg2-binary cryptography && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  # 3. L'interface de gestion de la Base de Données
  adminer:
    # Adminer remplace phpMyAdmin : il est plus léger et gère parfaitement PostgreSQL
    image: adminer
    restart: always
    ports:
      - "8082:8080" # Accessible sur http://localhost:8081
    depends_on:
      - db

volumes:
  central_data: