# ===============================================================================
# Fichier     : Dockerfile
# Rôle        : Recette de conteneurisation du backend Python
# Description :
#    Ce fichier définit l'environnement d'exécution isolé pour l'API FastAPI.
#    Il part d'une image système Python allégée (3.11-slim), installe les 
#    dépendances nécessaires définies dans le requirements.txt, copie le code 
#    source métier, et configure le serveur Uvicorn pour exposer le port 8000.
# ===============================================================================

# On part d'une version allégée de Python
FROM python:3.11-slim

# On définit le dossier de travail dans le conteneur
WORKDIR /app

# On copie la liste de courses
COPY requirements.txt .

# # On installe les outils système requis par apscheduler (gcc et tzdata)
# RUN apt-get update && apt-get install -y --no-install-recommends \
#     gcc \
#     libc6-dev \
#     tzdata \
#     && rm -rf /var/lib/apt/lists/*

# On installe les dépendances (dont FastAPI, SQLAlchemy, et la cryptographie)
RUN pip install --no-cache-dir -r requirements.txt

# On copie tout le reste de ton code source
COPY . .

# On expose le port de l'API
EXPOSE 8000

# La commande de démarrage
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]